/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dallasarivle
 */
public class v_Daftaraslab extends javax.swing.JFrame {

    /**
     * Creates new form v_homeBelumLogin
     */
    public v_Daftaraslab() {
        initComponents();
    }

//    public JButton tblPemroClicked() {
//        return tblPemro;
//    }
//
//    public JButton tblGISClicked() {
//        return tblGIS;
//    }
//
//    public JButton tblRPLClicked() {
//        return tblRPL;
//    }
//
//    public JButton tblBasdaClicked() {
//        return tblBasda;
//    }
//
//    public JButton tblLoginClicked() {
//        return tblLogin;
//    }
//    public String[] getDataCalon() {
//        String[] data = new String[8];
//        data[0] = this.nama.getText();
//        data[1] = this.nim.getText();
//        data[2] = this.alamat.getText();
//        data[3] = this.tahunLahir.getText();
//        data[4] = this.calonLab.getSelectedItem().toString();
//        data[5] = this.tahunDaftar.getText();
//        data[6] = this.usernameCalon.getText();
//        data[7] = this.passwordCalon.getText();
//        return data;
//    }
    public String getNamaCalon() {
        return nama.getText();
    }

    public String getNIM() {
        return nim.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getTahunLahir() {
        return tahunLahir.getText();
    }

    public int getCalonLab() {
        int calab = Integer.parseInt(calonLab.getSelectedItem().toString());
        if (calonLab.getSelectedItem().toString() == "Pemrograman") {
            calab = 1;
        } else if (calonLab.getSelectedItem().toString() == "Rekayasa Perangkat Lunak") {
            calab = 2;
        } else if (calonLab.getSelectedItem().toString() == "Basis Data") {
            calab = 3;
        } else if (calonLab.getSelectedItem().toString() == "GIS") {
            calab = 4;
        }
        return calab;
    }

    public String getTahunDaftar() {
        return tahunDaftar.getText();
    }

    public String getUsernamaCalon() {
        return usernameCalon.getText();
    }

    public String getPasswordCalon() {
        return passwordCalon.getText();
    }

    public JButton tblDaftarClicked() {
        return tbl_daftar;
    }

    public void pesan(String pesan) {
        JOptionPane.showMessageDialog(null, pesan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordCalon = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        usernameCalon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tbl_daftar = new javax.swing.JButton();
        tahunDaftar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        calonLab = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tahunLahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tblLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        tblPemro = new javax.swing.JButton();
        tblRPL = new javax.swing.JButton();
        tblGIS = new javax.swing.JButton();
        tblBasda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(passwordCalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 290, 40));

        jLabel12.setText("Password");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, -1, -1));
        getContentPane().add(usernameCalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 290, 40));

        jLabel11.setText("Username");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        tbl_daftar.setText("Daftar");
        getContentPane().add(tbl_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, -1, -1));
        getContentPane().add(tahunDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 660, 290, 40));

        jLabel10.setText("tahun daftar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 640, -1, -1));

        calonLab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "Pemrograman", "Rekayasa Perangkat Lunak", "GIS", "Basis Data" }));
        getContentPane().add(calonLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, 290, 40));

        jLabel9.setText("Laboratorium yang dipilih");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, -1));
        getContentPane().add(tahunLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 290, 40));

        jLabel8.setText("tahun lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, -1, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 290, 40));

        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, -1, -1));
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 290, 40));

        jLabel6.setText("NIM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 290, 40));

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lemon/Milk", 1, 10)); // NOI18N
        jLabel4.setText("Jadilah Bagian dari Kami!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 310, 30));

        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 350, 800));

        tblLogin.setText("Login");
        getContentPane().add(tblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Punya Akun? Silakan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        judul.setBackground(new java.awt.Color(0, 51, 153));
        judul.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(204, 204, 204));
        judul.setText("Laboratorium PSSI UNEJ");
        judul.setOpaque(true);
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        tblPemro.setBackground(new java.awt.Color(255, 51, 255));
        tblPemro.setText("Lab Pemrograman");
        tblPemro.setBorder(null);
        getContentPane().add(tblPemro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 440, 260));

        tblRPL.setBackground(new java.awt.Color(153, 204, 0));
        tblRPL.setText("Lab RPL");
        tblRPL.setBorder(null);
        getContentPane().add(tblRPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 440, 260));

        tblGIS.setBackground(new java.awt.Color(204, 204, 0));
        tblGIS.setText("Lab GIS");
        tblGIS.setBorder(null);
        getContentPane().add(tblGIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 440, 260));

        tblBasda.setBackground(new java.awt.Color(0, 51, 153));
        tblBasda.setText("Lab Basis Data");
        tblBasda.setBorder(null);
        getContentPane().add(tblBasda, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 440, 260));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Daftaraslab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Daftaraslab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Daftaraslab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Daftaraslab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Daftaraslab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> calonLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JPasswordField passwordCalon;
    private javax.swing.JTextField tahunDaftar;
    private javax.swing.JTextField tahunLahir;
    private javax.swing.JButton tblBasda;
    private javax.swing.JButton tblGIS;
    private javax.swing.JButton tblLogin;
    private javax.swing.JButton tblPemro;
    private javax.swing.JButton tblRPL;
    private javax.swing.JButton tbl_daftar;
    private javax.swing.JTextField usernameCalon;
    // End of variables declaration//GEN-END:variables
}
