/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author dallasarivle
 */
public class v_homeBelumLogin extends javax.swing.JFrame {

    /**
     * Creates new form v_homeBelumLogin
     */
    public v_homeBelumLogin() {
        initComponents();
    }

    public JButton tblPemroClicked() {
        return tblPemro;
    }

    public JButton tblGISClicked() {
        return tblGIS;
    }

    public JButton tblRPLClicked() {
        return tblRPL;
    }

    public JButton tblBasdaClicked() {
        return tblBasda;
    }

    public JButton tblLoginClicked() {
        return tblLogin;
    }

    public JButton tblDaftarClicked() {
        return tblDaftar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblDaftar = new javax.swing.JButton();
        tblLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        tblPemro = new javax.swing.JButton();
        tblRPL = new javax.swing.JButton();
        tblGIS = new javax.swing.JButton();
        tblBasda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDaftar.setText("Daftar Aslab");
        getContentPane().add(tblDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        tblLogin.setText("Login");
        getContentPane().add(tblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Punya Akun? Silakan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        judul.setBackground(new java.awt.Color(0, 102, 255));
        judul.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Laboratorium PSSI UNEJ");
        judul.setOpaque(true);
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        tblPemro.setBackground(new java.awt.Color(255, 204, 204));
        tblPemro.setText("Lab Pemrograman");
        tblPemro.setBorder(null);
        getContentPane().add(tblPemro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 440, 260));

        tblRPL.setBackground(new java.awt.Color(204, 255, 204));
        tblRPL.setText("Lab RPL");
        tblRPL.setBorder(null);
        getContentPane().add(tblRPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 440, 260));

        tblGIS.setBackground(new java.awt.Color(255, 255, 204));
        tblGIS.setText("Lab GIS");
        tblGIS.setBorder(null);
        getContentPane().add(tblGIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 440, 260));

        tblBasda.setBackground(new java.awt.Color(204, 204, 255));
        tblBasda.setText("Lab Basis Data");
        tblBasda.setBorder(null);
        getContentPane().add(tblBasda, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 440, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_homeBelumLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_homeBelumLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_homeBelumLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_homeBelumLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_homeBelumLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judul;
    private javax.swing.JButton tblBasda;
    private javax.swing.JButton tblDaftar;
    private javax.swing.JButton tblGIS;
    private javax.swing.JButton tblLogin;
    private javax.swing.JButton tblPemro;
    private javax.swing.JButton tblRPL;
    // End of variables declaration//GEN-END:variables
}
