/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author dallasarivle
 */
public class v_inputNilaiGIS extends javax.swing.JFrame {

    /**
     * Creates new form v_inputNilaiPemro
     */
    public v_inputNilaiGIS() {
        initComponents();
    }

    public String getNilaiMulmed() {
        String mulmed = this.nilaiMulmed.getSelectedItem().toString();
        if (this.nilaiMulmed.getSelectedItem().toString() == "<none>") {
            mulmed = " ";
        } else {
            mulmed = this.nilaiMulmed.getSelectedItem().toString();
        }
        return mulmed;
    }

    public String getNilaiJarkom() {
        String jarkom = this.nilaiJarkom.getSelectedItem().toString();
         if (this.nilaiJarkom.getSelectedItem().toString() == "<none>") {
            jarkom = " ";
        } else {
            jarkom = this.nilaiMulmed.getSelectedItem().toString();
        }
        return jarkom;
    }

    public String getNilaiAI() {
        String ai = this.nilaiAI.getSelectedItem().toString();
         if (this.nilaiAI.getSelectedItem().toString() == "<none>") {
            ai = " ";
        } else {
            ai = this.nilaiMulmed.getSelectedItem().toString();
        }
        return ai;
    }

    public JButton tblInput() {
        return tblinput;
    }
     public void pesan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nilaiAI = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nilaiMulmed = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nilaiJarkom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tblinput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nilaiAI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 270, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel1.setText("INput Nilai GIS");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jLabel2.setFont(new java.awt.Font("Lemon/Milk", 1, 12)); // NOI18N
        jLabel2.setText("Silakan Isi sesuai nilai Anda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel3.setText("Multimedia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        nilaiMulmed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiMulmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 270, 40));

        jLabel4.setText("Jaringan Komputer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        nilaiJarkom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiJarkom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, 40));

        jLabel5.setText("Artificial Intellegence");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        tblinput.setText("Input");
        getContentPane().add(tblinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiGIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiGIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiGIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiGIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_inputNilaiGIS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> nilaiAI;
    private javax.swing.JComboBox<String> nilaiJarkom;
    private javax.swing.JComboBox<String> nilaiMulmed;
    private javax.swing.JButton tblinput;
    // End of variables declaration//GEN-END:variables
}
