/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author dallasarivle
 */
public class v_inputNilaiPemro extends javax.swing.JFrame {

    /**
     * Creates new form v_inputNilaiPemro
     */
    public v_inputNilaiPemro() {
        initComponents();
    }

    public String getNilaiAlgo() {
        String algo = this.nilaiAlgo.getSelectedItem().toString();
        if (this.nilaiAlgo.getSelectedItem().toString() == "<none>") {
            algo = "";
        } else {
            algo = this.nilaiAlgo.getSelectedItem().toString();
        }
        return algo;
    }

    public String getNilaiAlgoII() {
        String algo2 = this.nilaiAlgo2.getSelectedItem().toString();
        if (this.nilaiAlgo2.getSelectedItem().toString() == "<none>") {
            algo2 = "";
        } else {
            algo2 = this.nilaiAlgo2.getSelectedItem().toString();
        }
        return algo2;
    }

    public String getNilaiPBO() {
        String pbo = this.nilaiPBO.getSelectedItem().toString();
        if (this.nilaiPBO.getSelectedItem().toString() == "<none>") {
            pbo = "";
        } else {
            pbo = this.nilaiPBO.getSelectedItem().toString();
        }
        return pbo;
    }

    public String getNilaiPBOII() {
        String pbo2 = this.nilaiPBO2.getSelectedItem().toString();
        if (this.nilaiPBO2.getSelectedItem().toString() == "<none>") {
            pbo2 = "";
        } else {
            pbo2 = this.nilaiPBO2.getSelectedItem().toString();
        }
        return pbo2;
    }

    public String getNilaiPemgraf() {
        String pemgraf = this.nilaiPemgraf.getSelectedItem().toString();
        if (this.nilaiPemgraf.getSelectedItem().toString() == "<none>") {
            pemgraf = "";
        } else {
            pemgraf = this.nilaiPemgraf.getSelectedItem().toString();
        }
        return pemgraf;
    }

    public String getNilaiWeb() {
        String web = this.nilaiWeb.getSelectedItem().toString();
        if (this.nilaiAlgo.getSelectedItem().toString() == "<none>") {
            web = "";
        } else {
            web = this.nilaiWeb.getSelectedItem().toString();
        }
        return web;
    }

    public JButton tblInput() {
        return tblinput;

    }

    public void pesan(String pesan) {
        JOptionPane.showMessageDialog(null, pesan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nilaiWeb = new javax.swing.JComboBox<>();
        nilaiPemgraf = new javax.swing.JComboBox<>();
        nilaiPBO2 = new javax.swing.JComboBox<>();
        nilaiPBO = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nilaiAlgo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nilaiAlgo2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tblinput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nilaiWeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 270, 40));

        nilaiPemgraf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiPemgraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 270, 40));

        nilaiPBO2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiPBO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 270, 40));

        nilaiPBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiPBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 270, 40));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel1.setText("INput Nilai PEmrograman");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jLabel2.setFont(new java.awt.Font("Lemon/Milk", 1, 12)); // NOI18N
        jLabel2.setText("Silakan Isi sesuai nilai Anda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel3.setText("Algoritma dan Struktur Data I");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        nilaiAlgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiAlgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 270, 40));

        jLabel4.setText("Algoritma dan Struktur Data II");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        nilaiAlgo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<none>", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));
        getContentPane().add(nilaiAlgo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, 40));

        jLabel5.setText("PBO I");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jLabel6.setText("PBO II");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jLabel7.setText("Pemgraf");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jLabel8.setText("Pemrograman Web");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        tblinput.setText("Input");
        getContentPane().add(tblinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 690, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiPemro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiPemro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiPemro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_inputNilaiPemro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_inputNilaiPemro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> nilaiAlgo;
    private javax.swing.JComboBox<String> nilaiAlgo2;
    private javax.swing.JComboBox<String> nilaiPBO;
    private javax.swing.JComboBox<String> nilaiPBO2;
    private javax.swing.JComboBox<String> nilaiPemgraf;
    private javax.swing.JComboBox<String> nilaiWeb;
    private javax.swing.JButton tblinput;
    // End of variables declaration//GEN-END:variables
}
